version: "3.1"

services:
  django:
    container_name: django
    build:
      dockerfile: ./Dockerfile.backend
    restart: always
    command: sh ./backend-entrypoint.sh
    env_file:
      - ./backend/.env
    environment:
      - DJANGO_SETTINGS_MODULE=presentations_project.settings
      - PYTHONUNBUFFERED=1
    volumes:
      - ./media:/usr/src/app/media 
    ports:
      - "8000:8000"
    depends_on:
      - pgdb
    # healthcheck:
    #   test: ["CMD-SHELL", "curl -f http://localhost:8000/ || exit 1"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5


  pgdb:
    image: postgres:17.4-alpine3.21
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=postgres
      - POSTGRES_DB=app
    container_name: pgdb
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    expose:
      - "5432"

  nginx:
    container_name: nginx
    build:
      dockerfile: ./Dockerfile.nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf.prod:/etc/nginx/nginx.conf
      - ./certbot/www/:/var/www/certbot/
      - ./certbot/conf/:/etc/letsencrypt/
      - ./media:/media
    depends_on:
      - django
      # django:
      #   condition: service_healthy
    restart: always

volumes:
  pgdata:
